<?php
// $Id$

/**
 * @defgroup domain_prefix Domain Prefix: dynamic table prefixing
 *
 * Allows for the dynamic table prefixing of selected database tables.
 */

/**
 * @file
 * Interface for selective table prefixing for use with Domain Access.
 *
 * @ingroup domain_prefix
 */

/**
 * Constant definitions for the various actions.
 */
define('DOMAIN_PREFIX_IGNORE', 1);
define('DOMAIN_PREFIX_CREATE', 2);
define('DOMAIN_PREFIX_COPY', 4);
define('DOMAIN_PREFIX_DROP', 8);
define('DOMAIN_PREFIX_UPDATE', 16);

/**
 * Implementats hook_domain_bootstrap_full().
 */
function domain_prefix_domain_bootstrap_full($domain) {
  $tables = array();
  $prefix = 'domain_'. $domain['domain_id'] .'_';
  $result = db_query("SELECT tablename FROM {domain_prefix} WHERE domain_id = %d AND status > %d", $domain['domain_id'], 1);
  while ($data = db_fetch_array($result)) {
    $tables[] = $data['tablename'];
  }
  if (!empty($tables)) {
    global $db_prefix;
    $new_prefix = array();
    // There might be global prefixing; if so, prepend the global.
    if (is_string($db_prefix)) {
      $new_prefix['default'] = $db_prefix;
      $prefix = $db_prefix . $prefix;
    }
    foreach ($tables as $table) {
      $new_prefix[$table] = $prefix;
    }
    $db_prefix = $new_prefix;
  }
}

/**
 * Implements hook_menu()
 */
function domain_prefix_menu() {
  $items = array();
  $items['admin/build/domain/prefix'] = array(
    'title' => 'Table prefixing',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer table prefixing'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('domain_prefix_configure_form'),
    'file' => 'domain_prefix.admin.inc',
  );
  $items['admin/build/domain/prefix/%domain'] = array(
    'title' => 'Domain prefix settings',
    'access arguments' => array('administer table prefixing'),
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('domain_prefix_form', 4),
    'file' => 'domain_prefix.admin.inc',
  );
  $items['domain_prefix_update'] = array(
    'title' => 'Domain prefix update',
    'access arguments' => array('administer table prefixing'),
    'type' => MENU_CALLBACK,
    'page callback' => 'domain_prefix_update',
    'file' => 'domain_prefix.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_perm
 */
function domain_prefix_perm() {
  return array('administer table prefixing');
}

/**
 * Implements hook_theme()
 */
function domain_prefix_theme() {
  $themes = array(
    'domain_prefix_configure_form' => array(
      'arguments' => array('form' => array()),
    ),
  );
  return $themes;
}

/**
 * Implementation of hook_enable().
 *
 * Register the domain_prefix with the domain module so it's loaded during domain
 * bootstrap and can implement domain_bootstrap hooks.
 */
function domain_prefix_enable() {
  domain_bootstrap_register();
}

/**
 * Implementation of hook_disable().
 */
function domain_prefix_disable() {
  domain_bootstrap_unregister('domain_prefix');
}

/**
 * Implements hook_domainlinks()
 *
 * @param $domain
 *  The currently active $domain array, provided by domain_lookup().
 */
function domain_prefix_domainlinks($domain) {
  if (user_access('administer table prefixing')) {
    $links[] = array(
      'title' => t('tables'),
      'path' => 'admin/build/domain/prefix/'. $domain['domain_id']
    );
    return $links;
  }
}

/**
 * Implements hook_domainupdate().
 */
function domain_prefix_domainupdate($op, $domain, $form_state = array()) {
  // Include the extra functions.
  include_once(drupal_get_path('module', 'domain_prefix') .'/domain_prefix.admin.inc');
  switch ($op) {
    case 'create':
      $rule = variable_get('domain_prefix_options', 1);
      if ($rule) {
        // Get the current settings.
        $settings = variable_get('domain_prefix', NULL);
        if (!empty($settings)) {
          $settings['domain_id'] = $domain['domain_id'];
          drupal_execute('domain_prefix_form', $form_state, $domain, $settings);
        }
      }
      break;
    case 'delete':
      domain_prefix_drop_records($domain['domain_id']);
      break;
  }
}

