<?php

/**
 * @file
 * Defines a Domain concept for use with Drupal.
 */

use Drupal\domain\Plugin\Core\Entity\Domain;
use Drupal\Core\Entity\EntityInterface;

/**
 * Set all affiliates as a default value for forms.
 */
const DOMAIN_ALL_AFFILIATES = 'DOMAIN_ALL_AFFILIATES';

/**
 * Set the current domain as a default value for forms.
 */
const DOMAIN_CURRENT_DOMAIN = 'DOMAIN_CURRENT_DOMAIN';

/**
 * Implements hook_permission().
 */
function domain_permission() {
  $permissions = array(
    'administer domains' => array(
      'title' => t('Administer all domain records'),
    ),
    'create domains' => array(
      'title' => t('Create domain records'),
    ),
    'edit assigned domains' => array(
      'title' => t('Edit assigned domain records'),
    ),
  );
  return $permissions;
}

/**
 * Implements hook_menu().
 */
function domain_menu() {
  $items['admin/structure/domain'] = array(
    'title' => 'Domains',
    'description' => 'Manage domain records for your installation.',
    'page callback' => 'domain_overview',
    // @TODO custom callback for per-domain access.
    'access arguments' => array('administer domains'),
    'file' => 'domain.admin.inc',
  );
  $items['admin/structure/domain/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/structure/domain/add'] = array(
    'title' => 'Add domain',
    'page callback' => 'domain_add',
    'access callback' => 'domain_create_access',
    'access arguments' => array(),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'domain.admin.inc',
  );
  $items['admin/structure/domain/%domain_machine_name'] = array(
    'title' => 'Domain',
    'page callback' => 'domain_edit',
    'page arguments' => array(3),
    'access callback' => 'domain_edit_access',
    'access arguments' => array(3),
    'type' => MENU_LOCAL_TASK,
    'file' => 'domain.admin.inc',
  );
  $items['admin/structure/domain/%domain_machine_name/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/structure/domain/%domain_machine_name/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'domain_delete',
    'page arguments' => array(3),
    'access callback' => 'domain_edit_access',
    'access arguments' => array(3),
    'type' => MENU_LOCAL_TASK,
    'file' => 'domain.admin.inc',
  );
  $items['admin/structure/domain/%domain_machine_name/default'] = array(
    'title' => 'Make default',
    'page callback' => 'domain_admin_callback',
    'page arguments' => array(3, 4),
    'access callback' => 'domain_edit_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
    'file' => 'domain.admin.inc',
  );
  $items['admin/structure/domain/%domain_machine_name/enable'] = array(
    'title' => 'Enable',
    'page callback' => 'domain_admin_callback',
    'page arguments' => array(3, 4),
    'access callback' => 'domain_edit_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
    'file' => 'domain.admin.inc',
  );
  $items['admin/structure/domain/%domain_machine_name/disable'] = array(
    'title' => 'Disable',
    'page callback' => 'domain_admin_callback',
    'page arguments' => array(3, 4),
    'access callback' => 'domain_edit_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
    'file' => 'domain.admin.inc',
  );
  $items['domain'] = array(
    'title' => 'Domains',
    'page callback' => 'domain_page',
    'access callback' => 'domain_create_access',
    'file' => 'domain.pages.inc',
  );
  $items['domain/%domain_machine_name'] = array(
    'title' => 'Domain',
    'title callback' => 'domain_page_title',
    'title arguments' => array(1),
    'page callback' => 'domain_page_view',
    'page arguments' => array(1),
    'access callback' => 'domain_view_access',
    'access arguments' => array(1),
    'file' => 'domain.pages.inc',
  );
  return $items;
}

/**
 * Checks to see if a user may create a new domain record.
 */
function domain_create_access() {
  if (user_access('administer domains') || user_access('create domains')) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Checks to see if a user may edit an existing domain record.
 */
function domain_edit_access() {
  // @TODO conditional check in the second permission.
  if (user_access('administer domains') || user_access('edit assigned domains')) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Checks to see if a user may view an existing domain record.
 */
function domain_view_access() {
  // @TODO conditional check in the second permission.
  if (user_access('administer domains') || user_access('edit assigned domains')) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Returns the page title for a domain record.
 *
 * @param Drupal\domain\Plugin\Core\Entity\Domain $domain
 *   A domain entity.
 */
function domain_page_title(Domain $domain) {
  return check_plain($domain->name);
}

/**
 * Implements hook_entity_bundle_info().
 */
function domain_entity_bundle_info() {
  $bundles['domain']['domain'] = array(
    'label' => t('Domain record'),
    'admin' => array(
      'path' => 'admin/structure/domain',
    ),
  );
  return $bundles;
}

/**
 * Implements hook_field_extra_fields().
 */
function domain_field_extra_fields() {
  $fields = array(
    'hostname' => array(
      'label' => t('Domain'),
      'description' => t('The domain hostname.'),
      'weight' => -12,
    ),
    'name' => array(
      'label' => t('Name'),
      'description' => t('Human-readable name.'),
      'weight' => -10,
    ),
    'scheme' => array(
      'label' => t('Scheme'),
      'description' => t('The host scheme.'),
      'weight' => -8,
    ),
    'status' => array(
      'label' => t('Status'),
      'description' => t('Record status.'),
      'weight' => -6,
    ),
    'weight' => array(
      'label' => t('Weight'),
      'description' => t('Sort weight.'),
      'weight' => -4,
    ),
    'is_default' => array(
      'label' => t('Default domain'),
      'description' => t('Indicates the default domain.'),
      'weight' => -2,
    ),
  );
  $extra['domain']['domain']['form'] = $fields;
  $extra['domain']['domain']['display'] = $fields;
  $extra['domain']['domain']['display']['domain_id'] = array(
    'label' => t('Id'),
    'description' => t('The domain record id.'),
    'weight' => -14,
  );
  dpm($extra);
  return $extra;
}

/**
 * Implements hook_field_info().
 */
function domain_field_info() {
  return array(
    'domain' => array(
      'label' => t('Domain'),
      'description' => t('This field stores a domain reference for an entity.'),
      'instance_settings' => array('all_affiliates' => TRUE),
      'default_widget' => 'domain',
      'default_formatter' => 'domain',
      'field item class' => '\Drupal\domain\Type\DomainItem',
    ),
  );
}

/**
 * Implements hook_field_is_empty().
 */
function domain_field_is_empty($item, $field) {
  if (empty($item) && (string) $item !== '0') {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_field_presave().
 *
 * @TODO: Should this logic move to setValue() in the Type class?
 */
function domain_field_presave(EntityInterface $entity, $field, $instance, $langcode, &$items) {
  // Handle field saves from an entity_load().
  if (isset($items[0]['realm'])) {
    $values = domain_extract_field_items($items, TRUE);
    if (!empty($values)) {
      foreach ($values as  $value) {
        $data[$value] = $value;
      }
    }
  }
  // Handles saves from a form checkbox set.
  else {
    $data = $items[0];
  }
  $result = array();
  $i = 0;
  if (!empty($data[DOMAIN_ALL_AFFILIATES])) {
    $result[$i]['realm'] = 'domain_site';
    $result[$i]['gid'] = 0;
    unset($data[DOMAIN_ALL_AFFILIATES]);
    $i++;
  }
  foreach (array_filter($data) as $key => $value) {
    if ($domain = domain_machine_name_load($key, TRUE)) {
      $result[$i]['realm'] = 'domain_id';
      $result[$i]['gid'] = $domain->domain_id;
      $i++;
    }
  }
  // Prepare items for saving.
  $items = $result;
  // Add domain information to the entity for storage, if required.
  // This approach is much simpler than trying to find the field instance.
  $entity->domain[$field['field_name']] = $result;
}

/**
 * Returns the id of the default domain.
 *
 * @return
 *   The domain_id of the default domain or FALSE if none is set.
 */
function domain_default_id() {
  $result = entity_load_multiple_by_properties('domain', array('is_default' => 1));
  if (!empty($result)) {
    return key($result);
  }
  return FALSE;
}

/**
 * Loads multiple domain records.
 *
 * @param array $domain_ids
 *   (optional) An array of entity IDs. If omitted, all entities are loaded.
 * @param bool $reset
 *   (optional) Whether to reset the internal cache.  Defaults to FALSE.
 *
 * @return array
 *   An array of domain entities indexed by domain_id.
 */
function domain_load_multiple(array $domain_ids = NULL, $reset = FALSE) {
  return entity_load_multiple('domain', $domain_ids, $reset);
}

/**
 * Return the domain entity matching a domain id.
 *
 * @param $domain_id
 *   The domain id.
 * @param bool $reset
 *   (optional) Whether to reset the internal cache. Defaults to FALSE.
 *
 * @return Drupal\domain\Plugin\Core\Entity\Domain|FALSE
 *   The domain entity, if exists, FALSE otherwise. Results are
 *   statically cached.
 */
function domain_load($domain_id = NULL, $reset = FALSE) {
  return entity_load('domain', $domain_id, $reset);
}

/**
 * Return the domain entity matching a domain machine name.
 *
 * @param $machine_name
 *   The domain's machine name.
 *
 * @return Drupal\domain\Plugin\Core\Entity\Domain|false
 *   The domain entity, if exists, FALSE otherwise. Results are
 *   statically cached.
 */
function domain_machine_name_load($machine_name) {
  $result = entity_load_multiple_by_properties('domain', array('machine_name' => $machine_name));
  return reset($result);
}

/**
 * Loads multiple domain records by machine name.
 *
 * @param array $machine_names
 *   (optional) An array of entity machine names. If omitted, all entities are loaded.
 * @param bool $reset
 *   (optional) Whether to reset the internal cache.  Defaults to FALSE.
 *
 * @return array
 *   An array of domain entities indexed by machine.
 */
function domain_machine_name_load_multiple(array $machine_names = NULL, $reset = FALSE) {
  $domains = array();
  if (!empty($machine_names)) {
    $result = entity_load_multiple_by_properties('domain', array('machine_name' => $machine_names));
  }
  else {
    $result = domain_load_multiple();
  }
  foreach ($result as $domain) {
    $domains[$domain->machine_name] = $domain;
  }
  return $domains;
}

/**
 * Saves a domain record.
 *
 * @param Drupal\domain\Plugin\Core\Entity\Domain $domain
 *   A domain entity.
 */
function domain_save(Domain $domain) {
  $domain->save();
}

/**
 * Creates a new Domain entity record with default values.
 *
 * @param $inherit
 *   Boolean flag indicating that the new domain should inherit values from the
 *   current $_SERVER request. Useful for creating domain records on install.
 *
 * @return Drupal\domain\Plugin\Core\Entity\Domain
 *   A domain entity, with preset values for the current environment.
 */
function domain_create($inherit = FALSE) {
  $default = domain_default_id();
  $domains = domain_load_multiple();
  $values = array(
    'scheme' => empty($GLOBALS['is_https']) ? 'http' : 'https',
    'status' => 1,
    'weight' => count($domains) + 1,
    'is_default' => (int) empty($default),
  );
  if ($inherit) {
    $values['hostname'] = $_SERVER['HTTP_HOST'];
    $values['name'] = variable_get('sitename', 'Drupal');
    $values['machine_name'] = domain_machine_name($values['hostname']);
  }
  $domain = entity_create('domain', $values);
  return $domain;
}

/**
 * Create a machine name for a domain record.
 *
 * @param $hostname
 *  The hostname string of the record, which should be unique.
 *
 * @return
 *  A string with dot and colon transformed to underscore.
 */
function domain_machine_name($hostname) {
  return preg_replace('/[^a-z0-9_]+/', '_', $hostname);
}

/**
 * Returns an array of required fields for a domain record.
 *
 * @return array
 *   An array of required field keys.
 */
function domain_required_fields() {
  return array('hostname', 'name', 'machine_name', 'scheme', 'status', 'weight');
}

/**
 * @TODO: move to a method.
 */
function domain_get_uri(Domain $domain) {
  return 'foo';
}

/**
 * Returns the current domain record.
 *
 * @TODO: this is a placeholder for testing.
 */
function domain_get_domain() {
  $active = domain_create(TRUE);
  return $active;
}

/**
 * Returns an array of domains for use in a form.
 *
 * @param boolean $filter
 *   Indicates whether the list should be filtered based on user permissions.
 *
 * @return array
 *   An array of domain values keyed by machine_name.
 */
function domain_options_list($filter = TRUE) {
  $list = array();
  $domains = domain_load_multiple();
  foreach ($domains as $domain) {
    // @TODO: filter this list.
    $list[$domain->machine_name] = $domain->name;
  }
  return $list;
}

/**
 * Reads an array of field items to domain records.
 *
 * @param array $items
 *   An $items array returned from a field element.
 * @param $keys
 *   Boolean indicator that only the matching keys should be returned.
 *   If set to FALSE, a $domain entity is returned for each record except for
 *   the DOMAIN_ALL_AFFILIATES constant.
 *
 * @return array
 *   An array of domains matching the values from the form element. Note that
 *   we are translating from machine_name to numeric gid for entity access.
 */
function domain_extract_field_items(array $items, $keys = FALSE) {
  $values = array();
  foreach ($items as $key => $value) {
    if ($value['realm'] == 'domain_site') {
      $values[DOMAIN_ALL_AFFILIATES] = DOMAIN_ALL_AFFILIATES;
    }
    elseif ($domain = domain_load($value['gid'])) {
      $values[$domain->machine_name] = $domain;
    }
  }
  if ($keys) {
    return array_keys($values);
  }
  return $values;
}

/**
 * Generates an array for rendering the given node.
 *
 * @param Drupal\domain\Plugin\Core\Entity\Domain $domain
 *   A domain entity.
 * @param $view_mode
 *   (optional) View mode, e.g., 'full', 'teaser'... Defaults to 'full.'
 * @param $langcode
 *   (optional) A language code to use for rendering. Defaults to NULL which is
 *   the global content language of the current request.
 *
 * @return
 *   An array as expected by drupal_render().
 */
function domain_view(Domain $domain, $view_mode = 'full', $langcode = NULL) {
  return entity_view($domain, $view_mode, $langcode);
}

/**
 * Constructs a drupal_render() style array from an array of loaded domains.
 *
 * @param $domains
 *   An array of domains as returned by domain_load_multiple().
 * @param $view_mode
 *   (optional) View mode, e.g., 'full', 'teaser'... Defaults to 'teaser.'
 * @param $langcode
 *   (optional) A language code to use for rendering. Defaults to the global
 *   content language of the current request.
 *
 * @return
 *   An array in the format expected by drupal_render().
 */
function domain_view_multiple($domains, $view_mode = 'teaser', $langcode = NULL) {
  return entity_view_multiple($domains, $view_mode, $langcode);
}
