<?php
// $id$

/**
 * @file
 *   Test module for Domain Access hooks.
 */

/**
 * Implements hook_domain_load().
 *
 * Add a 'test' variable to the domain array.
 */
function domain_test_domain_load(&$domain) {
  // Add a variable to the $domain array.
  $domain['testvar'] = TRUE;
}

/**
 * Implements hook_domain_insert().
 *
 * Change the sitename value to 'foobar'.
 */
function domain_test_domain_insert($domain, $form_values = array()) {
  if ($domain['sitename'] == 'testfoo') {
    db_update('domain')
      ->fields(array('sitename' => 'foobar'))
      ->condition('domain_id', $domain['domain_id'])
      ->execute();
  }
}

/**
 * Implements hook_domain_update().
 *
 * Change the sitename value to 'testfoo'.
 */
function domain_test_domain_update($domain, $form_values = array()) {
  if ($domain['sitename'] == 'foobar') {
    db_update('domain')
      ->fields(array('sitename' => 'testfoo'))
      ->condition('domain_id', $domain['domain_id'])
      ->execute();
  }
}
