<?php

/**
 * @file
 * Domain hook test module.
 */

/**
 * Implements hook_domain_load().
 */
function domain_test_domain_load(array $domains) {
  foreach ($domains as $domain) {
    $domain->addProperty('foo', 'bar');
  }
}

/**
 * Implements hook_domain_validate_alter().
 */
function domain_test_domain_validate_alter(&$error_list, $hostname) {
  // Deliberate test fail.
  if ($hostname == 'fail.example.com') {
    $error_list[] = 'Fail.example.com cannot be registered';
  }
}
