<?php

/**
 * @file
 * Pre-release updates hooks for Domain modules.
 */

/**
 * Update domain id to new value.
 */
function domain_alpha_update_8000(&$sandbox) {
  // Load all domains and update the id.
  $domains = \Drupal::entityTypeManager()->getStorage('domain')->loadMultiple();
  foreach ($domains as $domain) {
    /** @var $domain \Drupal\domain\Entity\Domain */
    $domain->createDomainId();
    $domain->save();
  }
  // Trigger permissions rebuild action.
  node_access_needs_rebuild(TRUE);
}
