<?php

/**
 * @file
 * Install file for the Domain User module
 */

/**
 * Implement hook_install()
 */
function domain_user_install() {
  drupal_install_schema('domain_user');
}

/**
 * Implement hook_schema()
 */
function domain_user_schema() {
  $schema['domain_user'] = array(
    'fields' => array(
      'domain_id' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
      'uid' => array('type' => 'int', 'not null' => TRUE, 'default' => 0)),
    'indexes' => array(
      'domain_id' => array('domain_id'),
      'uid' => array('uid')),
  );
  return $schema;
}

/**
 * Implement hook_uninstall()
 */
function domain_user_uninstall() {
  // Drop the storage table.
  drupal_uninstall_schema('domain_user');
  variable_del('domain_user');
  variable_del('domain_user_root');
  variable_del('domain_user_scheme');
  variable_del('domain_user_login');
  variable_del('domain_user_prefixing');
}
