<?php

/**
 * @file
 * Defines a Domain concept for use with Drupal.
 */

use Drupal\Core\Url;
use Drupal\domain\DomainInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_entity_bundle_info().
 */
function domain_entity_bundle_info() {
  $bundles['domain']['domain'] = array(
    'label' => t('Domain record'),
    'admin' => array(
      'real path' => 'admin/config/domain',
    ),
  );
  return $bundles;
}

/**
 * Entity URI callback.
 *
 * @param \Drupal\domain\DomainInterface $domain
 *   The Domain object.
 *
 * @return \Drupal\Core\Url
 *   The Domain URL.
 */
function domain_uri(DomainInterface $domain) {
  return Url::fromUri($domain->getPath(), ['absolute' => TRUE]);
}

/**
 * Implements hook_entity_load().
 *
 * The $domain->path and $domain->uri properties are derived from data in the
 * {domain} table. We use the hook system to load that data to indicate that
 * the data is not native to the object.
 *
 * This action is performed in hook_entity_load(), which precedes the running
 * of hook_domain_load() and ensures that our data is present for other modules.
 */
function domain_entity_load(array $entities, $entity_type) {
  if ($entity_type == 'domain') {
    foreach ($entities as $domain) {
      $domain->setPath();
      $domain->setUrl();
    }
  }
}

/**
 * Implements hook_help().
 */
function domain_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'domain.admin':
      $output = t('<p>The following domains have been created for your site.  The currently active domain
                     <strong>is shown in boldface</strong>. You may click on a domain to change the currently active domain.
                     </p>');
      return $output;
  }
}

/**
 * Implements hook_token_info().
 */
function domain_token_info() {
  return \Drupal::service('domain.token')->getTokenInfo();
}

/**
 * Implements hook_tokens().
 */
function domain_tokens($type, $tokens, array $data, array $options, \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata) {
  return \Drupal::service('domain.token')->getTokens($type, $tokens, $data, $options, $bubbleable_metadata);
}


/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function domain_preprocess_html(array &$variables) {
  // Add class to body tag, if set.
  $config = \Drupal::config('domain.settings');
  if ($string = $config->get('css_classes')) {
    $token = \Drupal::token();
    // Prepare the class properly.
    $variables['attributes']['class'][] = Html::getClass($token->replace($string));
  }
}
