<?php

/**
 * @file
 * Install, update and uninstall functions for the Domain Access module.
 */

/**
 * Implements hook_install().
 *
 * Installs the domain admin field on users.
 */
function domain_install() {
  _domain_configure_field();
}

/**
 * Implements hook_uninstall().
 *
 * Core does not properly purge field provided by configuration entities.
 * There are a few related issues and @todo notices in core to this effect.
 * Instead, we handle field purges ourselves.
 */
function domain_uninstall() {
  // Do a pass of purging on deleted Field API data, if any exists.
  $limit = \Drupal::config('field.settings')->get('purge_batch_size');
  field_purge_batch($limit);
  \Drupal::entityTypeManager()->clearCachedDefinitions();
}

/**
 * Implements hook_update_N().
 *
 * Installs the domain admin field on users.
 */
function domain_update_8001() {
  _domain_configure_field();
}

/**
 * Configures user form display to checkboxes widget for domain admin field.
 */
function _domain_configure_field() {
  if ($display = \Drupal::entityTypeManager()->getStorage('entity_form_display')->load('user.user.default')) {
    $display->setComponent(DOMAIN_ADMIN_FIELD, [
      'type' => 'options_buttons',
      'weight' => 50,
    ])->save();
  }
}
