<?php

/**
 * @file
 * Maps multiple host requests to a single domain record.
 */

/**
 * Implements hook_menu().
 */
function domain_alias_menu() {
  $items['admin/structure/domain/%domain/alias'] = array(
    'title' => 'Aliases',
    'route_name' => 'domain_alias',
  );
  return $items;
}

/**
 * Implements hook_domain_operations().
 */
function domain_alias_domain_operations(DomainInterface $domain) {
  // Add aliases to the list.
  $id = $domain->id();
  $operations['domain_alias'] = array(
    'title' => t('aliases'),
    'href' => "admin/structure/domain/$id/alias",
    'query' => array(),
  );
  return $operations;
}
