<?php

/**
 * @file
 * Install, update and uninstall functions for the Domain Alias module.
 */

/**
 * Updates domain_alias schema.
 */
function domain_alias_update_8001() {
  $manager = \Drupal::entityDefinitionUpdateManager();
  // Regenerate entity type indexes.
  $manager->updateEntityType($manager->getEntityType('domain_alias'));
}

/**
 * Adds domain_alias environment settings.
 */
function domain_alias_update_8002() {
  $config = \Drupal::service('config.factory')->getEditable('domain_alias.settings');
  // Set and save new message value.
  $config->set('environments', ['default', 'local', 'development', 'staging', 'testing'])->save();
}
