<?php
// $Id$

/**
 * @file
 * Install file.
 */

/**
 * Implements hook_install()
 */
function domain_conf_install() {
  drupal_install_schema('domain_conf');
}

/**
 * Implements hook_schema()
 */
function domain_conf_schema() {
  $schema['domain_conf'] = array(
    'fields' => array(
      'domain_id' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
      'settings' => array('type' => 'blob', 'not null' => FALSE)),
    'primary key' => array('domain_id'),
  );
  return $schema;
}

/**
 * Implements hook_uninstall()
 */
function domain_conf_uninstall() {
  drupal_uninstall_schema('domain_conf');
}
