<?php
// $Id$

/**
 * @file
 * Install file.
 */

/**
 * Implement hook_schema()
 */
function domain_conf_schema() {
  $schema['domain_conf'] = array(
    'description' => 'Stores custom settings for each domain.',
    'fields' => array(
      'domain_id' => array('type' => 'int', 'not null' => TRUE, 'default' => 0),
      'settings' => array('type' => 'blob', 'not null' => FALSE)),
    'primary key' => array('domain_id'),
    'foreign_keys' => array(
      'domain_id' => array('domain' => 'domain_id'),
    ),
  );
  return $schema;
}

/**
 * UPDATE FUNCTION
 *
 * Some variable names changed in Drupal 7.
 */

/**
 * Return an array of variable changes.
 */
function domain_conf_d7_variable_changes() {
  $removed = array(
    'menu_default_node_menu',
  );
  $renamed = array(
    'menu_primary_links_source' => 'menu_main_links_source',
  );
  return array('removed' => $removed, 'renamed' => $renamed);
}
