<?php

/**
 * @file
 * Install file for the Domain Settings module
 */

/**
 * Rename the variable 'domain_settings_ignore'.
 */
function domain_settings_update_6000() {
  // Get existing variable:
  $old_settings = variable_get('domain_settings_ignore', '');
  // Save the variable with another name if it exists:
  if (!empty($old_settings)) {
    variable_set('domain_settings_forms', $old_settings);
  }

  // Delete the old variable:
  variable_del('domain_settings_ignore');

  return t('Updated Domain Settings configuration.');
}
