<?php

/**
 * @file
 * Review content by assigned domain.
 */

use Drupal\domain\DomainInterface;
use Drupal\domain\DomainNegotiator;
use Drupal\Core\Url;

/**
 * Implements hook_domain_operations().
 */
function domain_content_domain_operations(DomainInterface $domain) {
  // Add content to the list.
  $account = \Drupal::currentUser();
  $id = $domain->id();
  if ($account->hasPermission('access domain content')) {
    $operations['domain_content'] = array(
      'title' => t('Content'),
      'url' => Url::fromUri("internal:/admin/content/domain-content/$id"),
      'weight' => 120, // Core operations start at 0 and increment by 10.
    );
  }
  if ($account->hasPermission('access domain content editors')) {
    $operations['domain_users'] = array(
      'title' => t('Editors'),
      'url' => Url::fromUri("internal:/admin/content/domain-editors/$id"),
      'weight' => 120, // Core operations start at 0 and increment by 10.
    );
  }

  return $operations;
}
