<?php

/**
 * @file
 * Domain-based access control for content.
 */

use Drupal\domain\DomainManager;
use Drupal\domain\DomainInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Defines the name of the node access control field.
 */
define('DOMAIN_ACCESS_NODE_FIELD', 'field_domain_access');

/**
 * Defines the names of the user assignment field.
 */
define('DOMAIN_ACCESS_USER_FIELD', 'field_domain_user');

/**
 * Implements hook_node_grants().
 */
function domain_access_node_grants($account, $op) {
  $grants = array();
  $active = domain_get_domain();
  if ($op == 'view') {
    $grants['domain_id'][] = $active->domain_id;
  }
  // @TODO grants for edit/delete.
  return $grants;
}

/**
 * Implements hook_node_access_records().
 */
function domain_access_node_access_records(NodeInterface $node) {
  foreach (domain_access_get_values($node) as $value) {
    if (isset($value['target_id']) && $domain = domain_load($value['target_id'])) {
      $grants[] = array(
        'realm' => 'domain_id',
        'gid' => $domain->domain_id,
        'grant_view' => 1,
        'grant_update' => 1,
        'grant_delete' => 1,
      );
    }
  }
  return $grants;
}

/**
 * Sets the default value for new fields.
 */
function domain_access_default_value($entity, $field, $instance, $langcode) {
  $item = array();
  if ($active = domain_get_domain()) {
    $item[0]['target_uuid'] = $active->uuid;
  }
  return $item;
}

/**
 * Pulls the domain access values from an entity.
 */
function domain_access_get_values($entity) {
  if ($entity->isNew()) {
    return array();
  }
  $values = $entity->getPropertyValues();
  return $values[DOMAIN_ACCESS_NODE_FIELD];
}

/**
 * Implements hook_node_presave().
 *
 * Fires only if Devel Generate module is present, to assign test nodes to
 * domains.
 *
 * @TODO: should we always set default values here?
 * @TODO: pull values from the Devel Generate form.
 *
 * @param \Drupal\Core\Entity\EntityInterface stdClass $node
 *   The node entity on which the operation is to be performed.
 */
function domain_access_node_presave(EntityInterface $node) {
  $exists = \Drupal::moduleHandler()->moduleExists('devel_generate');
  if ($exists && isset($node->devel_generate)) {
    // If set by the form.
    if (isset($node->devel_generate['domain_access'])) {
      $values = array(
        DOMAIN_ACCESS_NODE_FIELD => array_keys($node->devel_generate['domain_access']),
      );
    }
    // Else set randomly.
    else {
      $domains = domain_load_multiple();
      $values = array(
        DOMAIN_ACCESS_NODE_FIELD => array_rand($domains, ceil(rand(1, count($domains)))),
      );
    }
    $node->setPropertyValues($values);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function domain_access_form_devel_generate_content_form_alter(&$form, &$form_state, $form_id) {
  // Add our element to the devel generate form.
  $form['submit']['#weight'] = 10;
  $list = domain_options_list();
  $form['domain_access'] = array(
    '#title' => t('Domains'),
    '#type' => 'select',
    '#options' => $list,
    '#weight' => 2,
    '#multiple' => TRUE,
    '#size' => count($list) > 5 ? 5 : count($list),
    '#default_value' => array(domain_get_active_id()),
  );
}
