<?php

/**
 * @file
 * Install file for Domain Nav.
 */

/**
 * Implements hook_uninstall().
 */
function domain_nav_uninstall() {
  // Remove our variables.
  variable_del('domain_nav_block');
  variable_del('domain_nav_theme');
}

/**
 * Update block deltas to Drupal 7.
 */
function domain_nav_update_7000() {
  // Get an array of the renamed block deltas, organized by module.
  $renamed_deltas = array(
    'domain_nav' => array(
      '0' => 'default',
    ),
  );
  $moved_deltas = array();
  update_fix_d7_block_deltas($sandbox, $renamed_deltas, $moved_deltas);
  return t('Domain Access blocks updated.');
}
